--[[
  Playerbots BiS Tooltip - released under GNU GPL v2, matching mod-playerbots-bis.

  Adds to an item's tooltip the class/spec combinations that list it as best in
  slot, straight from the server's own playerbots_bis_item table. The data lives
  in BisData.lua, regenerated by tools/export_bis_tooltip.ps1, so the tooltip
  says exactly what the bots think - no second, drifting copy of the lists.

  Written for the 3.3.5a client: Lua 5.1, HookScript on OnTooltipSetItem, and no
  TooltipDataProcessor.
]]

local ADDON = "PlayerbotsBisTooltip"

-- Class ids as the server stores them. UnitClass() on 3.3.5 returns only the
-- localized name and the English token, never a numeric id, so the token is
-- what we map.
local CLASS_ID = {
    WARRIOR = 1, PALADIN = 2, HUNTER = 3, ROGUE = 4, PRIEST = 5,
    DEATHKNIGHT = 6, SHAMAN = 7, MAGE = 8, WARLOCK = 9, DRUID = 11,
}

local CLASS_NAME = {
    [1] = "Guerrier", [2] = "Paladin", [3] = "Chasseur", [4] = "Voleur",
    [5] = "Pretre", [6] = "Chevalier de la mort", [7] = "Chaman",
    [8] = "Mage", [9] = "Demoniste", [11] = "Druide",
}

-- Spec 10 on the Druid is the module's Bear sentinel: Bear and Cat share talent
-- tab 1, so the list separates them by a value the tab can never produce.
local SPEC_NAME = {
    [1] = { [0] = "Armes", [1] = "Fureur", [2] = "Protection" },
    [2] = { [0] = "Sacre", [1] = "Protection", [2] = "Vindicte" },
    [3] = { [0] = "Maitrise des betes", [1] = "Precision", [2] = "Survie" },
    [4] = { [0] = "Assassinat", [1] = "Combat", [2] = "Finesse" },
    [5] = { [0] = "Discipline", [1] = "Sacre", [2] = "Ombre" },
    [6] = { [0] = "Sang", [1] = "Givre", [2] = "Impie" },
    [7] = { [0] = "Elementaire", [1] = "Amelioration", [2] = "Restauration" },
    [8] = { [0] = "Arcanes", [1] = "Feu", [2] = "Givre" },
    [9] = { [0] = "Affliction", [1] = "Demonologie", [2] = "Destruction" },
    [11] = { [0] = "Equilibre", [1] = "Farouche", [2] = "Restauration", [10] = "Farouche (ours)" },
}

-- Rank 1 is the pick, 2 a solid alternative, 3 a stopgap. Colouring them saves
-- reading the number on a tooltip that is already busy.
local RANK_COLOR = {
    [1] = { 0.1, 1.0, 0.1 },
    [2] = { 1.0, 0.9, 0.2 },
    [3] = { 0.6, 0.6, 0.6 },
}

-- Same three ranks as hex, for the inline escapes the compact display uses. A
-- line that carries several classes cannot be coloured by AddLine's r,g,b.
-- Values copied from PlayerbotsBisBrowser: one rank, one colour, everywhere.
local RANK_HEX = {
    [1] = "1eff00",
    [2] = "ffe650",
    [3] = "999999",
}

-- The client's own class colours: recognising "Voleur" by its yellow costs no
-- reading at all, which is the whole point of the compact layout.
local CLASS_COLOR = {
    [1] = "c79c6e", [2] = "f58cba", [3] = "abd473", [4] = "fff569",
    [5] = "ffffff", [6] = "c41f3b", [7] = "0070de", [8] = "69ccf0",
    [9] = "9482c9", [11] = "ff7d0a",
}

-- Only the class whose full name is long enough to hurt on a shared line.
local CLASS_SHORT = {
    [6] = "DK",
}

-- Spec names trimmed to what still reads as that spec. Anything not listed
-- falls back to the full name, so a new spec never shows as a number.
local SPEC_SHORT = {
    [1] = { [2] = "Prot" },
    [2] = { [1] = "Prot" },
    [3] = { [0] = "Betes" },
    [4] = { [0] = "Assass" },
    [5] = { [0] = "Disci" },
    [7] = { [0] = "Elem", [1] = "Amelio", [2] = "Resto" },
    [9] = { [0] = "Afflic", [1] = "Demono", [2] = "Destru" },
    [11] = { [0] = "Equil", [2] = "Resto", [10] = "Ours" },
}

-- Tier ids are fixed by 01_playerbots_bis_tier.sql, so the short tags can be
-- keyed on them. TierShort() falls back to the server's own name for anything
-- added later.
local TIER_SHORT = {
    [10] = "Pre-Raid",       [20] = "P1 MC/Ony",      [30] = "P2 BWL",
    [40] = "P3 ZG",          [50] = "P4 AQ20",        [60] = "P5 AQ40",
    [70] = "P6 Naxx",
    [80] = "TBC Pre-Raid",   [90] = "TBC P1 Kara",    [100] = "TBC P2 SSC/TK",
    [110] = "TBC P3 Hyjal/BT", [120] = "TBC P4 Sunwell",
    [130] = "WotLK Pre-Raid", [140] = "WotLK P1 Naxx", [150] = "WotLK P2 Ulduar",
    [160] = "WotLK P3 EdC",  [170] = "WotLK P4 ICC",  [180] = "WotLK P5 CR",
}

local defaults = {
    allClasses = false,  -- false: only your own class, plus a one-line summary
    maxTier = 0,         -- 0: no ceiling. Mirror PlayerbotsBis.MaxTier to match the bots.
    compact = true,      -- one line per tier instead of one per class/spec/tier
    -- Only the highest tier an item reaches, not the phases it passed through.
    -- An item that is best in slot at Blackwing Lair AND at Molten Core says
    -- nothing useful with its Molten Core line; one that is pre-raid only still
    -- shows, since pre-raid is then its highest. Default on: the history is
    -- what people asked to stop reading.
    topOnly = true,
}

local db

-- Le plafond qui compte vraiment.
--
-- db.maxTier etait un reglage PUREMENT local, a 0 par defaut, et il fallait le
-- recopier a la main depuis PlayerbotsBis.MaxTier. Personne ne le fait, et le
-- symptome est trompeur : avec topOnly, "le palier le plus haut" devient une
-- phase que le serveur ne joue pas. Drake Fang Talisman, best in slot ZG pour
-- NEUF couples classe/spe, n'affichait qu'une ligne "TBC Pre-Raid Druide Ours"
-- - l'infobulle avait raison sur ses donnees et tort sur ce qui interesse.
--
-- L'export inscrit desormais le plafond du serveur dans BisData.lua. Il sert
-- de defaut, et un /pbbis maxtier explicite le remplace - c'est a ca que sert
-- maxTierManuel, sans quoi on ne saurait pas distinguer "jamais regle" de
-- "regle a zero expres".
local function PlafondEffectif()
    if db.maxTierManuel then
        return db.maxTier
    end
    return PlayerbotsBisTooltipServerMaxTier or 0
end

local function Print(msg)
    DEFAULT_CHAT_FRAME:AddMessage("|cff33ff99" .. ADDON .. "|r: " .. msg)
end

local function SpecName(class, spec)
    local specs = SPEC_NAME[class]
    return (specs and specs[spec]) or ("spe " .. tostring(spec))
end

local function ClassName(class)
    return CLASS_NAME[class] or ("classe " .. tostring(class))
end

local function TierName(tier)
    return (PlayerbotsBisTooltipTiers and PlayerbotsBisTooltipTiers[tier]) or ("palier " .. tostring(tier))
end

local function TierShort(tier)
    if TIER_SHORT[tier] then
        return TIER_SHORT[tier]
    end
    -- "Vanilla Phase 2 - Blackwing Lair" is the default wording; dropping the
    -- expansion keeps an unknown tier readable instead of merely shorter.
    return (string.gsub(TierName(tier), "^Vanilla ", ""))
end

local function ShortSpec(class, spec)
    local short = SPEC_SHORT[class]
    return (short and short[spec]) or SpecName(class, spec)
end

local function ShortClass(class)
    return CLASS_SHORT[class] or ClassName(class)
end

local function Tint(hex, text)
    return "|cff" .. hex .. text .. "|r"
end

local playerClassId

local function PlayerClassId()
    if not playerClassId then
        local _, token = UnitClass("player")
        playerClassId = CLASS_ID[token or ""] or 0
    end
    return playerClassId
end

-- Entries are stored flat, four numbers per row (class, spec, tier, rank), which
-- keeps a file of several thousand items small enough to parse at login.
--
-- Gather() turns those rows into tier -> class -> spec -> best rank. Both
-- displays read that same tree: the compact one walks it a tier at a time, the
-- detailed one flattens it back out.
local function Gather(itemId)
    local rows = PlayerbotsBisTooltipItems and PlayerbotsBisTooltipItems[itemId]
    if not rows then
        return nil
    end

    local myClass = PlayerClassId()
    local tiers, tierOrder = {}, {}
    local otherSpecs, otherOrder = {}, {}

    for i = 1, #rows, 4 do
        local class, spec, tier, rank = rows[i], rows[i + 1], rows[i + 2], rows[i + 3]
        local plafond = PlafondEffectif()
        if plafond == 0 or tier <= plafond then
            if db.allClasses or class == myClass then
                local entry = tiers[tier]
                if not entry then
                    entry = { classes = {}, order = {} }
                    tiers[tier] = entry
                    table.insert(tierOrder, tier)
                end

                local specs = entry.classes[class]
                if not specs then
                    specs = {}
                    entry.classes[class] = specs
                    table.insert(entry.order, class)
                end

                -- The same spec can appear twice for one tier (two lists, two
                -- ranks); the better rank is the one worth showing.
                if not specs[spec] or rank < specs[spec] then
                    specs[spec] = rank
                end
            else
                if not otherSpecs[class] then
                    otherSpecs[class] = {}
                    table.insert(otherOrder, class)
                end
                otherSpecs[class][spec] = true
            end
        end
    end

    if #tierOrder == 0 and #otherOrder == 0 then
        return nil
    end

    -- Best tier first: what the current phase says matters more than what an
    -- older one did.
    table.sort(tierOrder, function(a, b) return a > b end)
    table.sort(otherOrder)

    return {
        tiers = tiers,
        tierOrder = tierOrder,
        otherSpecs = otherSpecs,
        otherOrder = otherOrder,
    }
end

-- "Fureur/Prot", ranks coloured, best rank first.
local function SpecBlock(class, specs)
    local sorted = {}
    for spec, rank in pairs(specs) do
        table.insert(sorted, { spec = spec, rank = rank })
    end
    table.sort(sorted, function(a, b)
        if a.rank ~= b.rank then return a.rank < b.rank end
        return a.spec < b.spec
    end)

    -- The rank is written as well as coloured. Colour alone fails exactly when
    -- it matters: a line whose specs share one rank is a line of one colour,
    -- with nothing to compare it against.
    local names = {}
    for _, row in ipairs(sorted) do
        table.insert(names, Tint(RANK_HEX[row.rank] or RANK_HEX[3],
            ShortSpec(class, row.spec) .. " (" .. row.rank .. ")"))
    end
    return table.concat(names, "/")
end

-- One line per tier. "BiS" stays at the head of every line so the block is
-- still recognisable without a header line eating a row of its own.
local function AddCompactLines(tooltip, data)
    for i, tier in ipairs(data.tierOrder) do
        -- tierOrder is sorted highest first, so stopping after the first line
        -- leaves the phase that matters and drops the history behind it.
        if db.topOnly and i > 1 then return end
        local entry = data.tiers[tier]
        table.sort(entry.order)

        -- The class is always named, even when the line carries only yours:
        -- "Prot" alone does not say Prot of what, and the colour that was
        -- supposed to say it is the one thing a colour-blind eye loses first.
        local parts = {}
        for _, class in ipairs(entry.order) do
            table.insert(parts, Tint(CLASS_COLOR[class] or "ffffff", ShortClass(class))
                .. " " .. SpecBlock(class, entry.classes[class]))
        end

        -- Three spaces between classes, a slash inside one: the eye needs a
        -- wider gap between "Voleur Combat" and "Guerrier Fureur" than between
        -- two specs of the same class.
        tooltip:AddLine(Tint("ffd100", "BiS " .. TierShort(tier)) .. "  " .. table.concat(parts, "   "),
            1, 1, 1, true)
    end
end

-- Classes filtered out by /pbbis all, in one grey line. Same layout as above
-- minus the ranks, which are not tracked for classes you do not play.
local function AddOthersLine(tooltip, data)
    if #data.otherOrder == 0 then
        return
    end

    local parts = {}
    for _, class in ipairs(data.otherOrder) do
        local specs = {}
        for spec in pairs(data.otherSpecs[class]) do table.insert(specs, spec) end
        table.sort(specs)

        local names = {}
        for _, spec in ipairs(specs) do table.insert(names, ShortSpec(class, spec)) end
        table.insert(parts, Tint(CLASS_COLOR[class] or "ffffff", ShortClass(class))
            .. " " .. table.concat(names, "/"))
    end

    tooltip:AddLine(Tint("808080", "Aussi BiS :") .. " " .. table.concat(parts, "   "),
        0.5, 0.5, 0.5, true)
end

-- The pre-1.4 layout, kept behind /pbbis detail: one line per combination, with
-- the tier spelled out. Verbose, but it is the one that shows every rank number.
local function AddDetailedLines(tooltip, data)
    local flat = {}
    for i, tier in ipairs(data.tierOrder) do
        if db.topOnly and i > 1 then break end
        local entry = data.tiers[tier]
        for _, class in ipairs(entry.order) do
            for spec, rank in pairs(entry.classes[class]) do
                table.insert(flat, { class = class, spec = spec, tier = tier, rank = rank })
            end
        end
    end

    table.sort(flat, function(a, b)
        if a.tier ~= b.tier then return a.tier > b.tier end
        if a.rank ~= b.rank then return a.rank < b.rank end
        if a.class ~= b.class then return a.class < b.class end
        return a.spec < b.spec
    end)

    for _, row in ipairs(flat) do
        local color = RANK_COLOR[row.rank] or RANK_COLOR[3]
        tooltip:AddLine(string.format("BiS - %s %s - %s (rang %d)",
            ClassName(row.class), SpecName(row.class, row.spec), TierName(row.tier), row.rank),
            color[1], color[2], color[3])
    end
end

-- Qui porte cette piece en ce moment, d'apres le dernier .playerbotsbis report.
-- Le nom porte sa couleur de classe, comme partout ailleurs.
--
-- La donnee est un instantane, pas un flux : l'heure du releve est donc dite, et
-- c'est la seule chose qui empeche la ligne de mentir sans prevenir.
local function AddWearersLine(tooltip, itemId)
    if not PlayerbotsBisRoster_Wearers then
        return
    end

    local list, when = PlayerbotsBisRoster_Wearers(itemId)
    if not list or #list == 0 then
        return
    end

    local sorted = {}
    for _, w in ipairs(list) do table.insert(sorted, w) end
    table.sort(sorted, function(a, b) return a.name < b.name end)

    -- Au-dela, la ligne devient un mur : le nombre dit l'essentiel.
    local SHOWN_MAX = 8

    local names = {}
    for i = 1, math.min(#sorted, SHOWN_MAX) do
        local w = sorted[i]
        table.insert(names, Tint(CLASS_COLOR[w.cls] or "ffffff", w.name))
    end

    local text = Tint("40d040", "Porte par " .. #sorted .. " bot(s) :") .. " " .. table.concat(names, ", ")
    if #sorted > SHOWN_MAX then
        text = text .. Tint("808080", " et " .. (#sorted - SHOWN_MAX) .. " autre(s)")
    end
    if when and when ~= "" then
        text = text .. Tint("606060", "  (releve " .. when .. ")")
    end

    tooltip:AddLine(text, 1, 1, 1, true)
end

local function AddTooltipLines(tooltip, itemId)
    local data = Gather(itemId)

    if data then
        if db.compact then
            AddCompactLines(tooltip, data)
        else
            AddDetailedLines(tooltip, data)
        end
        AddOthersLine(tooltip, data)
    end

    -- Hors du test ci-dessus : la plupart de ce que portent quarante bots n'est
    -- sur aucune liste, et c'est justement pour ces pieces-la que la question
    -- "qui l'a deja ?" se pose.
    AddWearersLine(tooltip, itemId)

    tooltip:Show()  -- the frame must be resized around the lines we just added
end

local function OnTooltipSetItem(tooltip)
    if not db then
        return
    end

    local _, link = tooltip:GetItem()
    if not link then
        return
    end

    local itemId = tonumber(string.match(link, "item:(%d+)"))
    if not itemId then
        return
    end

    -- OnTooltipSetItem can fire more than once for the same item; without this
    -- guard the lines pile up every time.
    if tooltip.pbbtItem == itemId then
        return
    end
    tooltip.pbbtItem = itemId

    AddTooltipLines(tooltip, itemId)
end

local function OnTooltipCleared(tooltip)
    tooltip.pbbtItem = nil
end

local function HookTooltip(tooltip)
    if not tooltip then
        return
    end
    tooltip:HookScript("OnTooltipSetItem", OnTooltipSetItem)
    tooltip:HookScript("OnTooltipCleared", OnTooltipCleared)
end

SLASH_PLAYERBOTSBISTOOLTIP1 = "/pbbis"
SlashCmdList["PLAYERBOTSBISTOOLTIP"] = function(input)
    local cmd, arg = string.match(input or "", "^(%S*)%s*(.-)$")
    cmd = string.lower(cmd or "")

    if cmd == "all" then
        db.allClasses = not db.allClasses
        Print(db.allClasses and "toutes les classes affichees."
                             or "seulement ta classe, les autres en resume.")
    elseif cmd == "detail" or cmd == "compact" then
        db.compact = not db.compact
        Print(db.compact and "infobulle compacte : une ligne par palier."
                          or "infobulle detaillee : une ligne par classe, spe et palier.")
    elseif cmd == "top" then
        db.topOnly = not db.topOnly
        Print(db.topOnly and "infobulle : seulement le palier le plus haut."
                          or "infobulle : tous les paliers, du plus haut au plus bas.")
    elseif cmd == "maxtier" then
        local n = tonumber(arg)
        if arg == "auto" then
            db.maxTierManuel = nil
            local serveur = PlayerbotsBisTooltipServerMaxTier or 0
            Print("plafond repris du serveur : "
                  .. (serveur == 0 and "aucun" or serveur) .. ".")
        elseif n and n >= 0 then
            db.maxTier = n
            db.maxTierManuel = true
            Print(n == 0 and "aucun plafond de palier."
                          or ("paliers au-dessus de " .. n .. " masques."))
        else
            Print("usage : /pbbis maxtier <nombre> | auto, 0 pour aucun plafond.")
        end
    elseif cmd == "jets" or cmd == "roll" or cmd == "rolls" then
        if PlayerbotsBisRolls_Command then
            PlayerbotsBisRolls_Command(arg)
        else
            Print("jets automatiques indisponibles - PlayerbotsBisRolls.lua n'est pas charge.")
        end
    elseif cmd == "compo" then
        if PlayerbotsBisCompo_Command then
            PlayerbotsBisCompo_Command(arg)
        else
            Print("compositions indisponibles - PlayerbotsBisCompo.lua n'est pas charge.")
        end
    elseif cmd == "roster" or cmd == "bots" then
        if PlayerbotsBisRoster_Toggle then
            PlayerbotsBisRoster_Toggle()
        else
            Print("fenetre d'etat indisponible - PlayerbotsBisRoster.lua n'est pas charge.")
        end
    elseif cmd == "raids" or cmd == "raid" then
        if PlayerbotsBisRaids_Toggle then
            PlayerbotsBisRaids_Toggle()
        else
            Print("fenetre des raids indisponible - PlayerbotsBisRaids.lua n'est pas charge.")
        end
    elseif cmd == "inspect" then
        if PlayerbotsBisInspect_Diag then
            PlayerbotsBisInspect_Diag()
        else
            Print("|cffff2020PlayerbotsBisInspect.lua n'est pas charge.|r Le fichier"
                  .. " est NEUF : un /reload ne suffit pas, il faut quitter et"
                  .. " relancer le client apres la copie de l'addon.")
        end
    elseif cmd == "bilan" then
        if PlayerbotsBisRoster_Bilan then
            PlayerbotsBisRoster_Bilan(string.lower(arg or ""))
        else
            Print("bilan indisponible - PlayerbotsBisRoster.lua n'est pas charge.")
        end
    elseif cmd == "minimap" then
        local said = false
        if PlayerbotsBisBrowser_ToggleMinimap then
            local shown = PlayerbotsBisBrowser_ToggleMinimap()
            Print(shown and "bouton listes affiche." or "bouton listes masque.")
            said = true
        end
        if PlayerbotsBisRoster_ToggleMinimap then
            local shown = PlayerbotsBisRoster_ToggleMinimap()
            Print(shown and "bouton etat des bots affiche." or "bouton etat des bots masque.")
            said = true
        end
        if not said then
            Print("boutons de minicarte indisponibles.")
        end
    elseif cmd == "" then
        -- Bare command opens the browser: it is what you reach for most, and
        -- the numbers below are one word away.
        if PlayerbotsBisBrowser_Toggle then
            PlayerbotsBisBrowser_Toggle()
        else
            Print("navigateur indisponible - PlayerbotsBisBrowser.lua n'est pas charge.")
        end
    else
        local count = 0
        if PlayerbotsBisTooltipItems then
            for _ in pairs(PlayerbotsBisTooltipItems) do count = count + 1 end
        end
        Print(count .. " objets charges.")
        -- Le bot lit la base en direct, l'infobulle lit ce fichier. Un export
        -- oublie apres un import SQL les fait diverger en silence, et c'est
        -- toujours la base qui a raison : la date dit laquelle croire.
        if PlayerbotsBisTooltipStamp then
            Print("exportes le " .. PlayerbotsBisTooltipStamp
                  .. " - si un bot annonce un BiS absent de l'infobulle, relance"
                  .. " tools/export_bis_tooltip.ps1 puis /reload.")
        else
            Print("date d'export inconnue (BisData.lua d'avant cette version) -"
                  .. " relance tools/export_bis_tooltip.ps1 puis /reload.")
        end
        Print("/pbbis - ouvre le navigateur des listes (aussi /pbbislist)")
        Print("/pbbis all - bascule entre ta classe seule et toutes les classes (actuel : "
              .. (db.allClasses and "toutes" or "ta classe") .. ")")
        Print("/pbbis detail - bascule compact / detaille (actuel : "
              .. (db.compact and "compact" or "detaille") .. ")")
        Print("En compact, le rang suit la spe entre parentheses et la colore : "
              .. "|cff1eff00(1)|r, |cffffe650(2)|r, |cff999999(3)|r.")
        Print("/pbbis top - n'affiche que le palier le plus haut (actuel : "
              .. (db.topOnly and "oui" or "non") .. ")")
        -- Without a ceiling, "highest" can mean a phase the server does not
        -- play: a cape listed at Blackwing Lair AND at Ahn'Qiraj would show
        -- only the Ahn'Qiraj line, which is the one piece of news nobody can
        -- act on.
        local plafond = PlafondEffectif()
        if db.topOnly and plafond == 0 then
            Print("|cffffcc00Sans plafond, 'le plus haut' peut designer une phase que ton "
                  .. "serveur ne joue pas - et l'infobulle masque alors le palier qui "
                  .. "t'interesse. Mets /pbbis maxtier <n>, ou reexporte BisData.lua "
                  .. "avec -MaxTier pour que le plafond vienne du serveur.|r")
        end
        Print("/pbbis maxtier <n> | auto - masque les paliers superieurs a n (actuel : "
              .. (plafond == 0 and "aucun plafond" or plafond)
              .. ", " .. (db.maxTierManuel and "regle ici" or "repris du serveur") .. ")")
        Print("/pbbis roster - etat BiS des bots (rempli par .playerbotsbis report)")
        Print("/pbbis inspect - pourquoi le compte BiS ne s'affiche pas a l'inspection")
        Print("/pbbis bilan - ce que les bots ont gagne depuis le repere")
        Print("/pbbis bilan depart - pose le repere ici (avant de partir en raid)")
        Print("/pbbis raids - quel raid rapporte quoi, et a quels bots (aussi /pbbisraids)")
        Print("/pbbis compo - enregistre et reapplique une repartition de raid")
        Print("/pbbis jets - jets automatiques sur les bijoux de Zul'Gurub")
        Print("/pbbis minimap - affiche ou masque le bouton de minicarte")
        Print("/pbbis info - ce resume")
    end
end

local frame = CreateFrame("Frame")
frame:RegisterEvent("ADDON_LOADED")
frame:SetScript("OnEvent", function(_, _, name)
    if name ~= ADDON then
        return
    end

    PlayerbotsBisTooltipDB = PlayerbotsBisTooltipDB or {}
    db = PlayerbotsBisTooltipDB
    for k, v in pairs(defaults) do
        if db[k] == nil then
            db[k] = v
        end
    end

    if not PlayerbotsBisTooltipItems then
        Print("BisData.lua est absent ou vide - relance tools/export_bis_tooltip.ps1.")
        return
    end

    HookTooltip(GameTooltip)
    HookTooltip(ItemRefTooltip)
    HookTooltip(ShoppingTooltip1)
    HookTooltip(ShoppingTooltip2)
    HookTooltip(ShoppingTooltip3)
end)
