--[[
  Playerbots BiS Tooltip - released under GNU GPL v2, matching mod-playerbots-bis.

  Adds to an item's tooltip the class/spec combinations that list it as best in
  slot, straight from the server's own playerbots_bis_item table. The data lives
  in BisData.lua, regenerated by tools/export_bis_tooltip.ps1, so the tooltip
  says exactly what the bots think - no second, drifting copy of the lists.

  Written for the 3.3.5a client: Lua 5.1, HookScript on OnTooltipSetItem, and no
  TooltipDataProcessor.
]]

local ADDON = "PlayerbotsBisTooltip"

-- Class ids as the server stores them. UnitClass() on 3.3.5 returns only the
-- localized name and the English token, never a numeric id, so the token is
-- what we map.
local CLASS_ID = {
    WARRIOR = 1, PALADIN = 2, HUNTER = 3, ROGUE = 4, PRIEST = 5,
    DEATHKNIGHT = 6, SHAMAN = 7, MAGE = 8, WARLOCK = 9, DRUID = 11,
}

local CLASS_NAME = {
    [1] = "Guerrier", [2] = "Paladin", [3] = "Chasseur", [4] = "Voleur",
    [5] = "Pretre", [6] = "Chevalier de la mort", [7] = "Chaman",
    [8] = "Mage", [9] = "Demoniste", [11] = "Druide",
}

-- Spec 10 on the Druid is the module's Bear sentinel: Bear and Cat share talent
-- tab 1, so the list separates them by a value the tab can never produce.
local SPEC_NAME = {
    [1] = { [0] = "Armes", [1] = "Fureur", [2] = "Protection" },
    [2] = { [0] = "Sacre", [1] = "Protection", [2] = "Vindicte" },
    [3] = { [0] = "Maitrise des betes", [1] = "Precision", [2] = "Survie" },
    [4] = { [0] = "Assassinat", [1] = "Combat", [2] = "Finesse" },
    [5] = { [0] = "Discipline", [1] = "Sacre", [2] = "Ombre" },
    [6] = { [0] = "Sang", [1] = "Givre", [2] = "Impie" },
    [7] = { [0] = "Elementaire", [1] = "Amelioration", [2] = "Restauration" },
    [8] = { [0] = "Arcanes", [1] = "Feu", [2] = "Givre" },
    [9] = { [0] = "Affliction", [1] = "Demonologie", [2] = "Destruction" },
    [11] = { [0] = "Equilibre", [1] = "Farouche", [2] = "Restauration", [10] = "Farouche (ours)" },
}

-- Rank 1 is the pick, 2 a solid alternative, 3 a stopgap. Colouring them saves
-- reading the number on a tooltip that is already busy.
local RANK_COLOR = {
    [1] = { 0.1, 1.0, 0.1 },
    [2] = { 1.0, 0.9, 0.2 },
    [3] = { 0.6, 0.6, 0.6 },
}

local defaults = {
    allClasses = false,  -- false: only your own class, plus a one-line summary
    maxTier = 0,         -- 0: no ceiling. Mirror PlayerbotsBis.MaxTier to match the bots.
}

local db

local function Print(msg)
    DEFAULT_CHAT_FRAME:AddMessage("|cff33ff99" .. ADDON .. "|r: " .. msg)
end

local function SpecName(class, spec)
    local specs = SPEC_NAME[class]
    return (specs and specs[spec]) or ("spe " .. tostring(spec))
end

local function ClassName(class)
    return CLASS_NAME[class] or ("classe " .. tostring(class))
end

local function TierName(tier)
    return (PlayerbotsBisTooltipTiers and PlayerbotsBisTooltipTiers[tier]) or ("palier " .. tostring(tier))
end

local playerClassId

local function PlayerClassId()
    if not playerClassId then
        local _, token = UnitClass("player")
        playerClassId = CLASS_ID[token or ""] or 0
    end
    return playerClassId
end

-- Entries are stored flat, four numbers per row (class, spec, tier, rank), which
-- keeps a file of several thousand items small enough to parse at login.
local function BuildLines(itemId)
    local rows = PlayerbotsBisTooltipItems and PlayerbotsBisTooltipItems[itemId]
    if not rows then
        return nil
    end

    local mine = {}
    local otherSpecs, otherOrder = {}, {}
    local myClass = PlayerClassId()

    for i = 1, #rows, 4 do
        local class, spec, tier, rank = rows[i], rows[i + 1], rows[i + 2], rows[i + 3]
        if db.maxTier == 0 or tier <= db.maxTier then
            if db.allClasses or class == myClass then
                table.insert(mine, { class = class, spec = spec, tier = tier, rank = rank })
            else
                if not otherSpecs[class] then
                    otherSpecs[class] = {}
                    table.insert(otherOrder, class)
                end
                otherSpecs[class][spec] = true
            end
        end
    end

    -- The summary names the specs too. One line per item either way, and
    -- "Druide" alone does not answer the only question worth asking about
    -- another class's BiS: which of its specs.
    local others = {}
    table.sort(otherOrder)
    for _, class in ipairs(otherOrder) do
        local specs = {}
        for spec in pairs(otherSpecs[class]) do table.insert(specs, spec) end
        table.sort(specs)

        local names = {}
        for _, spec in ipairs(specs) do table.insert(names, SpecName(class, spec)) end
        -- "Classe - spe, spe ; Classe - spe" rather than parentheses: the druid
        -- bear sentinel is already named "Farouche (ours)", and nesting that
        -- inside another pair of brackets reads badly.
        table.insert(others, ClassName(class) .. " - " .. table.concat(names, ", "))
    end

    if #mine == 0 and #others == 0 then
        return nil
    end

    -- Best tier first: what the current phase says matters more than what an
    -- older one did.
    table.sort(mine, function(a, b)
        if a.tier ~= b.tier then return a.tier > b.tier end
        if a.rank ~= b.rank then return a.rank < b.rank end
        if a.class ~= b.class then return a.class < b.class end
        return a.spec < b.spec
    end)

    return mine, others
end

local function AddTooltipLines(tooltip, itemId)
    local mine, others = BuildLines(itemId)
    if not mine then
        return
    end

    for _, row in ipairs(mine) do
        local color = RANK_COLOR[row.rank] or RANK_COLOR[3]
        tooltip:AddLine(string.format("BiS - %s %s - %s (rang %d)",
            ClassName(row.class), SpecName(row.class, row.spec), TierName(row.tier), row.rank),
            color[1], color[2], color[3])
    end

    if others and #others > 0 then
        tooltip:AddLine("Aussi BiS pour : " .. table.concat(others, " ; "), 0.5, 0.5, 0.5, true)
    end

    tooltip:Show()  -- the frame must be resized around the lines we just added
end

local function OnTooltipSetItem(tooltip)
    if not db then
        return
    end

    local _, link = tooltip:GetItem()
    if not link then
        return
    end

    local itemId = tonumber(string.match(link, "item:(%d+)"))
    if not itemId then
        return
    end

    -- OnTooltipSetItem can fire more than once for the same item; without this
    -- guard the lines pile up every time.
    if tooltip.pbbtItem == itemId then
        return
    end
    tooltip.pbbtItem = itemId

    AddTooltipLines(tooltip, itemId)
end

local function OnTooltipCleared(tooltip)
    tooltip.pbbtItem = nil
end

local function HookTooltip(tooltip)
    if not tooltip then
        return
    end
    tooltip:HookScript("OnTooltipSetItem", OnTooltipSetItem)
    tooltip:HookScript("OnTooltipCleared", OnTooltipCleared)
end

SLASH_PLAYERBOTSBISTOOLTIP1 = "/pbbis"
SlashCmdList["PLAYERBOTSBISTOOLTIP"] = function(input)
    local cmd, arg = string.match(input or "", "^(%S*)%s*(.-)$")
    cmd = string.lower(cmd or "")

    if cmd == "all" then
        db.allClasses = not db.allClasses
        Print(db.allClasses and "toutes les classes affichees."
                             or "seulement ta classe, les autres en resume.")
    elseif cmd == "maxtier" then
        local n = tonumber(arg)
        if n and n >= 0 then
            db.maxTier = n
            Print(n == 0 and "aucun plafond de palier."
                          or ("paliers au-dessus de " .. n .. " masques."))
        else
            Print("usage : /pbbis maxtier <nombre>, 0 pour aucun plafond.")
        end
    elseif cmd == "minimap" then
        if PlayerbotsBisBrowser_ToggleMinimap then
            local shown = PlayerbotsBisBrowser_ToggleMinimap()
            Print(shown and "bouton de minicarte affiche." or "bouton de minicarte masque.")
        else
            Print("bouton de minicarte indisponible.")
        end
    elseif cmd == "" then
        -- Bare command opens the browser: it is what you reach for most, and
        -- the numbers below are one word away.
        if PlayerbotsBisBrowser_Toggle then
            PlayerbotsBisBrowser_Toggle()
        else
            Print("navigateur indisponible - PlayerbotsBisBrowser.lua n'est pas charge.")
        end
    else
        local count = 0
        if PlayerbotsBisTooltipItems then
            for _ in pairs(PlayerbotsBisTooltipItems) do count = count + 1 end
        end
        Print(count .. " objets charges.")
        Print("/pbbis - ouvre le navigateur des listes (aussi /pbbislist)")
        Print("/pbbis all - bascule entre ta classe seule et toutes les classes (actuel : "
              .. (db.allClasses and "toutes" or "ta classe") .. ")")
        Print("/pbbis maxtier <n> - masque les paliers superieurs a n (actuel : "
              .. (db.maxTier == 0 and "aucun plafond" or db.maxTier) .. ")")
        Print("/pbbis minimap - affiche ou masque le bouton de minicarte")
        Print("/pbbis info - ce resume")
    end
end

local frame = CreateFrame("Frame")
frame:RegisterEvent("ADDON_LOADED")
frame:SetScript("OnEvent", function(_, _, name)
    if name ~= ADDON then
        return
    end

    PlayerbotsBisTooltipDB = PlayerbotsBisTooltipDB or {}
    db = PlayerbotsBisTooltipDB
    for k, v in pairs(defaults) do
        if db[k] == nil then
            db[k] = v
        end
    end

    if not PlayerbotsBisTooltipItems then
        Print("BisData.lua est absent ou vide - relance tools/export_bis_tooltip.ps1.")
        return
    end

    HookTooltip(GameTooltip)
    HookTooltip(ItemRefTooltip)
    HookTooltip(ShoppingTooltip1)
    HookTooltip(ShoppingTooltip2)
    HookTooltip(ShoppingTooltip3)
end)
